### ISSUE TITLE
make issue

### ISSUE THREAD

**Issue by Hong-333** [YuxuanXie/caffe_mobilessd#1]
Hi, I have a problem with caffe make

![image](https://user-images.githubusercontent.com/40624715/70874313-f5877d00-1ff4-11ea-8ba8-fe81392a62c7.png)

gcc = 7.4.0
cuda = 10.2
cudnn = 7.6.5

Why does this error occur?

**Comment by Hong-333** [comment]
gpu is not available?

**Comment by YuxuanXie** [comment]
Sorry, I just test the CPU version. GPU is not available.

**Comment by Hong-333** [comment]
> Sorry, I just test the CPU version. GPU is not available.

I checked with the CPU version.

I want to quantize the Mobilenet ssd I learned, is this correct?
![image](https://user-images.githubusercontent.com/40624715/71218496-0d1c7980-2305-11ea-9018-6b4d3708acdb.png)

**Comment by YuxuanXie** [comment]
Its not correct because the loss is too big. Do you generate the table file based on your model?

**Comment by Hong-333** [comment]
> Its not correct because the loss is too big. Do you generate the table file based on your model?

No I do not use table files. just train.prototxt and mymodel.caffemodel 
based on mobilenetv1+ssd original

**Comment by YuxuanXie** [comment]
No, you cannot train directly in 8 bits. You should train your model in float type and generate table files based on your trained model. And then quantize. This is 8-bit quantization that I did here.

**Comment by Hong-333** [comment]
> No, you cannot train directly in 8 bits. You should train your model in float type and generate table files based on your trained model. And then quantize. This is 8-bit quantization that I did here.

How do I generate a table file?

**Comment by YuxuanXie** [comment]
https://github.com/BUG1989/caffe-int8-convert-tools

**Comment by Hong-333** [comment]
> https://github.com/BUG1989/caffe-int8-convert-tools

thank you for your reply!

I want to make a dynamic-fixed-point 8bit
Is it the same as int8 and dynamic-fixed-point 8bit?

**Comment by YuxuanXie** [comment]
Ok, I see. Its not the same in fact. In int8 we use KL divergency but not dynamic fixed point 8 bit. Because the loss of dfp 8 bit is very huge.

**Comment by YuxuanXie** [comment]
U can see that my 16 bits quantization is dynamic fixed point.

**Comment by YuxuanXie** [comment]
If u want to use 8 bits dynamic fixed point quantization, just change 16 to 8. Thats it

**Comment by Hong-333** [comment]
> If u want to use 8 bits dynamic fixed point quantization, just change 16 to 8. Thats it

That's the result of changing from 16 to 8 in quantize.cpp.

https://drive.google.com/file/d/11_gZhajiNEoaCWj4bDG-GB1n0kI2q6K0/view?usp=sharing
https://drive.google.com/file/d/15aEtbqUO45x3tnnrPu52eW8KTctlGcBJ/view?usp=sharing

this is my prototxt,caffemodel 
there's something wrong with prototxt?

**Comment by YuxuanXie** [comment]
Its right. But u should get a quantized prototxt file after you run.

**Comment by Hong-333** [comment]
![image](https://user-images.githubusercontent.com/40624715/71343742-0d867000-25a4-11ea-8b3a-0aa78e75087f.png)

The accuracy is ridiculously low. I don't understand.

i just changed 16 to 8 in quantize.cpp

i want fine tune mobilenet+ssd in 8bit dynamic-fixed-point  :(

**Comment by YuxuanXie** [comment]
Did you test 16 bits? There should be no loss for 16 bits dynamic fixed quantization.
